### ISSUE TITLE
Include a picture of the animal

### ISSUE THREAD

**Issue by nsylv** [aluo-x/813_site#14]
And ability to upload one in the "new animal" dialog

**Comment by ramimanna** [comment]
this would only be visible in the modal, (but we could potentially have a small "profile pic"-like image in the table. Pros: it would aid the user to find a certain animal / person faster by profile pic recognition. Cons: it might look a bit out of place in the table? not sure.

**Comment by nsylv** [comment]
@ramimanna  Saw the pictures added to the table - I think that looks great!

Several considerations:
* have to add picture upload to the modals
** how to upload a picture (can we save it in the firestore?  do they have to provide a url?)
** add the upload into the modal
* we need to make the pictures column not sortable (I think there's a DataTables option somewhere for that)

**Comment by ramimanna** [comment]
yeah! so i made the pictures column not sortable :)
i'm storing the images as base64 strings for simplicity, so they're stored in the firestore just like any other string data. I know how to create a file upload for base64 images, i just haven't added it to the modals because I know you're making a lot of changes to the modals.

**Comment by nsylv** [comment]
this is now in and looks great 🖼
